### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by GeoffreyEmery** [Azure-Samples/active-directory-node-webapi#13]
I think this easiest way to get started with this is if you just put it all in a docker image and then just told us were to replace the config.. i know what would have helped me out.

**Comment by brandwe** [comment]
I'm looking in to that. Thanks for the suggestion!

**Comment by derisen** [comment]
Closing this issue as there's a more recent sample [here](https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2)
