### ISSUE TITLE
Calls to any endpoint apart from / result in a 401 unauthorised

### ISSUE THREAD

**Issue by tomhallam** [Azure-Samples/active-directory-node-webapi#18]
Hi,

I can't seem to figure out how to request the login screen to access the API - I seem to always hit Unauthorised whether that be in the browser or via `curl`. 

I followed the setup instructions exactly and the server starts, just don't seem to be able to get any further. The last line in the application console is:

```
[2016-05-27T13:11:22.243Z]  INFO: AzureAD: Metadata Parser/6624 on local: Parsing JSON retreived from the signing keys endpoint.
```

Any help would be appreciated.

**Comment by derisen** [comment]
Closing this issue as there's a more recent sample [here](https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2)
