### ISSUE TITLE
when i run the code it ask me client id cannot be empty where i have to give client id 

### ISSUE THREAD

**Issue by subhans3tech** [Azure-Samples/active-directory-node-webapi#19]
client is app id of azure directory

**Comment by poojaKarande13** [comment]
The options in app.js file should be as following:
 
var options = {
     audience: config.creds.audience,
     validateIssuer: config.creds.validateIssuer,
     passReqToCallback: config.creds.passReqToCallback,
    loggingLevel: config.creds.loggingLevel
    clientID: config.creds.clientID
 };

clientID is missing

**Comment by subhans3tech** [comment]
thanks

**Comment by rmetcalf9** [comment]
This is a normal part of setup - Why isn't it documented in the README??????
