### ISSUE TITLE
Upgrade to Restify 5

### ISSUE THREAD

**Issue by blandine** [Azure-Samples/active-directory-node-webapi#24]
Restify has removed the CORS part from the core library in version 5. 
The [restify cors middleware plugin](https://github.com/Tabcorp/restify-cors-middleware) must be used instead. ([cf restify migration doc](http://restify.com/docs/4to5/))

It would be nice to upgrade this sample with the new version of Restify.
Thanks :)

**Comment by derisen** [comment]
Closing this issue as there's a more recent sample [here](https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2)
