### ISSUE TITLE
Token Validation on the API

### ISSUE THREAD

**Issue by lizetpena** [Azure-Samples/active-directory-node-webapi#28]
Hi, 
I downloaded this code sample to share it with a group of developers and noticed there is no token server side validation? Am I missing the location of this validation?
Also, the only endpoint that is defined on the configuration is the metadata endpoint for AAD. Why?

Thank you.

Sincerely.

**Comment by brandwe** [comment]
Hello @lizetpena - the token validation happens using a library that is included in the sample called  `passport-azure-ad` library. 

It is at this location: https://github.com/AzureAD/passport-azure-ad/blob/dev/lib/jsonWebToken.js

Hope this helps!
