### ISSUE TITLE
APP ID URI？

### ISSUE THREAD

**Issue by MasayukiIida** [Azure-Samples/active-directory-node-webapi#30]
I am trying to setup the sample server, but sumbled at app registeration.

What do i enter for "REDIRECT URI" ?
 http://localhost:8888/
 http://localhost:8888/login
 http://localhost:8888/auth/provider/callback

Also, if I have to edit the manifest, could someone please tell me exactly which URL goes to which variables?

Thank you :)

**Comment by derisen** [comment]
Closing this issue as there's a more recent sample [here](https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2)

For application registration, please consult the documentation [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app)
