### ISSUE TITLE
Please mention installing Python (>= v2.5.0 & < 3.0.0) and setting env variables PythonPath=C:\Python27 and Python=%PythonPath%\Python.exe as a pre-requisite

### ISSUE THREAD

**Issue by anujc** [Azure-Samples/active-directory-node-webapi#5]
npm install fails with error

dir\WebAPI-Nodejs\node-server\node_modules\r
estify\node_modules\dtrace-provider>node "C:\Program Files\nodejs\node_modules\n
pm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:101:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd dir\WebAPI-Nodejs\node-server\n
ode_modules\restify\node_modules\dtrace-provider
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2

**Comment by GeoffreyEmery** [comment]
agree on this .. got blocked for a at 30 minutes debuging this

**Comment by brandwe** [comment]
I assume this is a Windows issue only. Runs fine on OS X. I'll update README.

**Comment by subhans3tech** [comment]
thanks

**Comment by derisen** [comment]
Closing this issue as there's a more recent sample [here](https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2)
